[tool.codespell]
count = ''
quiet-level = 3
skip = './.*,*.csv,*.json,*.pyc,./docs/_build/*,./htmlcov/*,*.egg-info,atom.xml,feed.xml,docs,*.pdf,Gemfile.lock,./source/assets/built/*,./source/node_modules/*'
ignore-words = '.codespell_ignore'
