source "https://rubygems.org"

# gem "jekyll", "~> 3.9.0"
# gem "github-pages", "~> 214"
gem "github-pages", "~> 214", group: :jekyll_plugins
# gem "github-pages", "~> 226", group: :jekyll_plugins
# gem "rake", "~> 13.0.3"
gem "slugify", "~> 1.0.7"
