source "https://rubygems.org"

# gem "jekyll", "~> 3.9.0"
gem "github-pages", "~> 214"

gem "jekyll-feed", "~> 0.12"
gem "slugify", "~> 1.0.7"
gem "jekyll-paginate"

gem 'jekyll-sitemap'


# gem "github-pages", "~> 214", group: :jekyll_plugins
# gem "github-pages", "~> 226", group: :jekyll_plugins
# gem "rake", "~> 13.0.3"


# group :jekyll_plugins do
#     gem "jekyll-feed", "~> 0.12"
#     gem "slugify", "~> 1.0.7"
#     gem "jekyll-paginate"
# end
